"""Broadcast analytics: blast impact, high-blast senders, attention metrics."""

import polars as pl


def compute_blast_impact(message_fact: pl.DataFrame) -> pl.DataFrame:
    """Compute blast impact: total recipient-impressions generated by high-recipient messages."""
    # Classify messages by recipient count tiers
    classified = message_fact.with_columns([
        pl.when(pl.col("n_recipients") == 1).then(pl.lit("1:1"))
        .when(pl.col("n_recipients") <= 5).then(pl.lit("small_group"))
        .when(pl.col("n_recipients") <= 20).then(pl.lit("medium_blast"))
        .otherwise(pl.lit("large_blast"))
        .alias("blast_tier"),
    ])

    # Aggregate by tier
    tier_stats = (
        classified.group_by("blast_tier")
        .agg([
            pl.len().alias("msg_count"),
            pl.col("n_recipients").sum().alias("total_impressions"),
            pl.col("size_bytes").sum().alias("total_bytes"),
            pl.col("n_recipients").mean().alias("avg_recipients"),
        ])
    )

    return tier_stats


def compute_high_blast_senders(
    message_fact: pl.DataFrame,
    threshold: int = 10,
) -> pl.DataFrame:
    """Identify senders who frequently send to many recipients."""
    blasts = message_fact.filter(pl.col("n_recipients") > threshold)

    sender_blasts = (
        blasts.group_by("from_email")
        .agg([
            pl.len().alias("blast_count"),
            pl.col("n_recipients").mean().alias("avg_blast_recipients"),
            pl.col("n_recipients").max().alias("max_recipients"),
            pl.col("n_recipients").sum().alias("total_blast_impressions"),
        ])
        .sort("blast_count", descending=True)
    )

    return sender_blasts


def compute_recipient_distribution(message_fact: pl.DataFrame) -> pl.DataFrame:
    """Compute the distribution of recipient counts across all messages."""
    dist = (
        message_fact.group_by("n_recipients")
        .agg(pl.len().alias("msg_count"))
        .sort("n_recipients")
    )

    total = dist["msg_count"].sum()
    dist = dist.with_columns([
        (pl.col("msg_count") / total * 100).alias("pct"),
        (pl.col("msg_count").cum_sum() / total * 100).alias("cumulative_pct"),
    ])

    return dist
